name: PR Commenter Bot

on:
  push:
    branches:
      - main

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Action Folder
        uses: ./.github/actions/action.yml
